library(KoNLP)
library(wordcloud)
useSejongDic()
data1<-readLines("certificate.txt")
data1
data2<-sapply(data1,extractNoun,USE.NAMES = F)
data2
data3<-unlist(data2)
data3<-Filter(function(x) {nchar(x)<=10},data3)
head(unlist(data3),30)
data3<-gsub("\\d+","",data3)##
data3<-gsub("요약","",data3)
data3<-gsub("내용","",data3)
data3<-gsub("\\.","",data3)
data3<-gsub(" ","",data3)
data3<-gsub("오늘","",data3)
data3<-gsub("하기","",data3)
data3<-gsub("때문","",data3)
data3<-gsub("친구","",data3)
data3<-gsub("가지","",data3)
data3<-gsub("경우","",data3)
data3<-gsub("하게","",data3)
data3<-gsub("누구","",data3)
data3<-gsub("들이","",data3)
data3<-gsub("하시","",data3)
data3<-gsub("안녕","",data3)
data3<-gsub("커플","",data3)
data3<-gsub("하나","",data3)
data3<-gsub("정도","",data3)
data3<-gsub("\\'","",data3)
write(unlist(data3),"certificate_2.txt")
data4<-read.table("certificate_2.txt")
data4
nrow(data4)
wordcount<-table(data4)
wordcount
head(sort(wordcount,decreasing=T),20)

data3
data3<-Filter(function(x) {nchar(x)>=2},data3)
write(unlist(data3),"remake_2.txt")
data4<-read.table("remake_2.txt")
data4
nrow(data4)
wordcount<-table(data4)
wordcount
head(sort(wordcount,decreasing = T),20)
library(RColorBrewer)
palete<-brewer.pal(9,"Set3")
wordcloud(names(wordcount),freq=wordcount,scale=c(5,1),rot.per=0.8,min.freq=3,random.order = F,random.color=T,colors=palete)
legend(0.3,1,"자격증 키워드",cex=0.8, fill=NA,border=NA,bg="white",text.col='red',text.font=2,box.col="red")
