마크다운 연습
=============================
이 자료는 마크다운 문법을 연습해보는 것이다.
제목에 대하여
-----------------------------
제목은 ====와 ----로 표시할 수 있다.

#제목1
#제목#

## 제목2
### 제목3
#### 제목4

단락(본문)
-----------------------

단락은 특별한 기호 없이 그대로 사용한다. 특별한 경우가 아니라면 들여쓰기를 하지 않는다.

단락과 단락 사이는 하나 이상의 빈 줄로 구분한다.

임의로 줄을 바꾸기 위해서는 
두개 이상의 빈칸(space)를 쓴 다음 새로운 줄을 쓴다.

순서가 없는 목록
-----------------
*수박
*참외
-호박
-오이

순서가 있는 목록
-----------------
1.수박
2.참외
3.호박
4.오이

어떤 목록이 다른 목록을 품고 있는 경우
--------------------------------------
1.Item 1
2.Item 2
3.Item 3
      *Item 3a
      *Item 3b

강조
----
*italc* **bold**
_italc_- **bold**

인용문단
--------
> 다른 곳에서 인용했다는 표시를 하기위해 > 기호를 쓴다.

##컴퓨터 코드

블록 코드는 백틱 3개로 구분한다.
인라인 코드는 백틱 1개로 구분한다.
백틱은 보통 키보드에서 좌특 상단 TAB키 위에 있다.

```
This text is displayed verbatim /preformatted
```

we defined the `add` function to 
compute the sim of two numbers. 

```{r}
summary(cars)

library(ggplot2)
qplot(data=mpg,x=drv,fill=drv)
```

인라인 청크
-----------

인라인 청크는 `r 1+1`로 쓴다.

히스토그램
-----------

```{r normaldis, fig.width=7, fig.height=5}

a<-rnorm(1000)
hist(a,col='orange')
```

이전에 했던 계산을 다시 수행하지 않게 하기
```{r normaldis1, fig.width=7,fig.height=5,chche=TRUE}
a<-rnorm(1000)
hist(a,col='orange')
```

코드를 실행 시킬지 여부를 결정
------------------------------

코드만 보이기
```{r eval=FALSE}

a<-rnorm(1000)
hist(a,col='orange')
```

결과로 보이기
```{r eval=TRUE}

a<-rnorm(1000)
hist(a,col='orange')
```
